### ISSUE TITLE
Estudo e implementação de CI/CD

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#144]
## Descrição da Issue
Implementação de CI para auxiliar ao desenvolvimento.

## Tasks:
- [x] Estudar sobre CI's
- [x] Impementar CI

## Critérios de Aceitação:
- [x] Estar funcionando

**Comment by matheuscvp** [comment]
Para o Ci implementamos um .yml tanto no back quanto no front, que é chamado em todo pull request, para fazer os testes unitarios, e mostrar um log no git hub actions
