### ISSUE TITLE
Melhoria da Visão Lógica 

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#159]
## Descrição da Issue
Realizar modificações no tópico visão lógica do documento de arquitetura para deixar claro a utilização do Django/DjangoRest

## Tasks:
- [x] Editar imagem

## Critérios de Aceitação:
- [x] Imagem estar de fácil assimilação para entender o funcionamento

**Comment by CarlosFiuza** [comment]
Edição no fluxograma de visão lógica realizada para facilitar entendimento e assimilação
