### ISSUE TITLE
Melhoria do Canvas

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#160]
## Descrição da Issue
Refatorar o Canvas para evoluir a ideia de um negócio viável.

## Tasks:
- [x] Evoluir o canvas

## Critérios de Aceitação:
- [x] Ideia de negócio ser mais concreta

**Comment by Joao-Moura** [comment]
Todos da equipe se reuniram em call para a refatoração do canvas, com exceção do Vitor Lamego que ficou responsável por fazer a review.
