### ISSUE TITLE
Estudar Metodologias Ágeis

### ISSUE THREAD

**Issue by VitorLamego** [fga-eps-mds/MDS-2020-2-G6#2]
- [x] Estudar as cerimônias do SCRUM

- [x] Estudar os papéis no SCRUM

- [x] Estudar sobre metodologia ágeis em geral

- [x] Elaborar um documento com os assuntos estudados mais relevantes e disponibilizar para o restante do grupo.

**Comment by CarlosFiuza** [comment]
Estudo sobre metodologias ágeis em geral realizado. Anotações seram adicionadas no documento ao final.

**Comment by VitorLamego** [comment]
Foi feito o estudo de metodologias ágeis em geral e também algumas em específico como o SCRUM, XP e o Kanban. A seguir segue um documento com alguns dos pontos mais importantes encontrados na pesquisa.

Caso exista a necessidade de alteração em alguma parte do documento sintam-se à vontade para realizá-la.

Documento Metodologia Ágeis: https://docs.google.com/document/d/1svNgyVxK6u-w-UtBZZEqhKYOYsQGYn1YfrzhOjYc7pY/edit?usp=sharing
