### ISSUE TITLE
Deixar anúncio invisível

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#219]
## Descrição da Issue
- Adicionar funcionalidade ao botão de deixar o anúncio invisível.

## Tasks:
- [x] Implementar funcionalidade ao botão

## Critérios de Aceitação:
- [x] Tentar manter % de coverage dos testes

**Comment by CarlosFiuza** [comment]
Adicionada funcionalidade de clicar no botão de deixar anúncio visível ou não para os compradores.
