### ISSUE TITLE
Deploy na Play Store

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#222]
## Descrição da Issue
- Publicar app na google play

## Tarefas a realizar
- [x] Fazer alterações necessárias para publicar na play store
- [x] Publicar na play store
- [x] Link do app no README's

**Comment by matheuscvp** [comment]
Alterações no App feitas localmente, para a geração do app bundle(arquivo necessário para a publicação)

**Comment by matheuscvp** [comment]
Publicação do app na google play store pedido, esperando analise pela google play.

**Comment by matheuscvp** [comment]
Publicado no link [Hortum](https://play.google.com/store/apps/details?id=com.hortum_mobile.mds)
