### ISSUE TITLE
Fazer Release 2

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#237]
## Descrição da Issue
- Reunir grupo para definir os tópicos e fazer apresentação.

## Tasks:
- [x] Definir tópicos
- [x] Fazer os slides
- [x] Gravar vídeo
- [x] Editar vídeo
- [x] Publicar vídeo
- [x] Adicionar ao repositório os links

**Comment by matheuscvp** [comment]
video publicado no link: https://youtu.be/Ml5eWDkkGzE
