### ISSUE TITLE
Número de telefone aos detalhes do produtor

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#238]
## Descrição da Issue
- Adicionar telefone aos detalhes do produtor

## Tasks:
- [x] Refatorar tela detalhes do produtor

## Critérios de Aceitação:
- [x] Alterar tela do produtor adicionando campo do telefone cadastrado

**Comment by CarlosFiuza** [comment]
Adicionado número do produtor na página de detalhes do produtor, com o objetivo de possibilitar a comunicação com comprador com o produtor
