### ISSUE TITLE
Revisão das User Stories

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#28]
## Descrição da Issue
O Grupo deve revisar todas as user stories criadas, bem como os épicos e features.

## Tasks:
- [x] Revisar documentação

## Critérios de Aceitação:
- [x] Ser aceito por todos os membros

**Comment by VitorLamego** [comment]
Dei uma olhada agora nas User Stories e acho que a gente precisa conversar um pouco mais para detalhar algumas coisas, para então evitar qualquer tipo de abstração dentro dessas US que podem virar problema lá na frente. Mas acho que a ideia como um todo é realmente o que está lá, só precisa especificar alguns pontos.

**Comment by brenno-silva** [comment]
O grupo se reuniu no dia 26 de Fevereiro de 2021 e definiu as Features, Épicos e User Stories a serem trabalhadas no projeto.
