### ISSUE TITLE
Organizar o GitHub

### ISSUE THREAD

**Issue by brenno-silva** [fga-eps-mds/MDS-2020-2-G6#3]
- [x] Estudar comandos Git
- [x] Organizar repositório
- [x] Estudar licenças
- [x] Estudar guias sobre open-source
- [x] Gerar documentação sobre Git/Github(Funcionalidades, boas práticas e como usar)

**Comment by Joao-Moura** [comment]
Para a organização do repositório

- [x] LICENSE
- [x] CONTRIBUTING
- [x] CODE_OF_CONDUCT
- [x] templates de issues/questões/PR

**Comment by Joao-Moura** [comment]
[**Documento sobre git/github**](https://docs.google.com/document/d/1Yag212ywRfYKjlzXtt0N6reGQAWH6Xwl9mpN5C9DnhI/edit?usp=sharing)
