### ISSUE TITLE
Estudo sobre documento de visão e arquitetura

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/MDS-2020-2-G6#6]
- [x] Pesquisar sobre documentos de visão
- [x] Olhar dv de repositórios antigos da matéria
- [x] Documentar para o grupo sobre esse tema

**Comment by Joao-Moura** [comment]
- [x] Estudar também sobre documentos de arquitetura.

**Comment by brenno-silva** [comment]
[Guia da IBM](https://www.ibm.com/support/knowledgecenter/pt-br/SSYMRC_6.0.3/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html)
[Exemplo Lino](https://github.com/fga-eps-mds/2018.2-Lino/blob/master/docs/documento-de-visao.md)
[Exemplo Quero Cultura](https://github.com/fga-eps-mds/2017.2-QueroCultura/wiki/Documento-de-Vis%C3%A3o)

**Comment by Joao-Moura** [comment]
[Template de Documento de Arquitetura](https://github.com/DroidFoundry/DroidMetronome/wiki/TEMPLATE-Documento-de-Arquitetura-de-Software)
[Exemplo Acácia](https://fga-eps-mds.github.io/2019.2-Acacia/#/architecture_document)
[Exemplo IndicaAi](https://fga-eps-mds.github.io/2018.2-IndicaAi//docs/2018/08/28/architecture-doc.html)

**Comment by brenno-silva** [comment]
[Artigo sobre documentação de arquitetura](http://www.linhadecodigo.com.br/artigo/3343/como-documentar-a-arquitetura-de-software.aspx)
